<a href="https://colab.research.google.com/github/19PA1A0278/AI/blob/readme/19PA1A0278_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXPERIMENT-1 1.NUMPY i.Different ways to create Numpy arrays

In [1]:
import numpy as np
a = np.array([5,6,7])
print (a)

[5 6 7]


In [2]:
a = np.array([[1,2],[5,8]])
print (a)

[[1 2]
 [5 8]]


ii.Add,remove,modify elements in an array

In [3]:
newArray = np.append(a,[11,22,33])
print(newArray)

[ 1  2  5  8 11 22 33]


In [4]:
import numpy as np
l=np.array([1,2,3,4,5])
l=np.delete(l,3)
print(l)

[1 2 3 5]


In [5]:
b=np.array([2,3,4,1,5,6])
b[b<2]=-1
print(b)

[ 2  3  4 -1  5  6]


In [6]:
import numpy as np
v=np.random.random((8,8))
n=np.random.random((8,8))
sum=np.add(v,n)
diff=np.subtract(v,n)
prod=np.multiply(v,n)
quo=np.divide(v,n)
mod=np.mod(v,n)
pow=np.power(v,n)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[0.82452664 0.53590075 1.10289205 1.23002731 0.87035375 1.00365283
  1.28928128 1.29735768]
 [1.54532278 1.2725266  1.00216867 0.97904369 1.32509888 1.39129157
  1.32427528 1.30070121]
 [1.57435373 0.81650213 1.18768596 0.98129041 0.97466429 1.43491003
  1.24006827 1.28732985]
 [0.66203911 1.4226408  1.44723156 1.41191242 1.54471249 1.08011072
  0.85851814 1.24517274]
 [0.9715619  0.95849099 1.27460374 0.41396567 1.65450633 0.97339349
  0.53084601 0.67600445]
 [1.34418188 0.22056937 0.61204998 1.57430547 1.20726175 0.70380467
  0.59778767 1.50983033]
 [0.68826613 1.64271113 1.53907045 1.16410956 1.59309771 0.74942681
  1.69744931 1.1915665 ]
 [1.02781557 1.07335256 1.2675349  0.92968154 0.78252663 0.89626511
  1.42262965 0.40048891]]
[[ 0.79007251 -0.02631645  0.7078483  -0.34778505  0.64473491 -0.07863711
   0.00433038  0.36822661]
 [-0.04668506 -0.17163462 -0.67486021  0.23722464 -0.16002807 -0.07459226
  -0.47699733  0.33909199]
 [-0.04790773 -0.65378584  0.25187411 -0.51022673 -0.

iv.Slicing and iterating of numpy arrays

slicing

In [7]:
import numpy as np
arr=np.array([1,3,5,7,9])
print(arr[1:3])

[3 5]


iterating

In [8]:
for i in arr:
 print(i)


1
3
5
7
9
